server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123@qwe
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates/